validator:
  index: 0
  name: "validator-0"

network:
  listen_addr: "127.0.0.1:9000"
  peers:
    - "/ip4/127.0.0.1/tcp/9001/p2p/12D3KooWH3uVF6wv47WnArKHk5p6cvgCJEb74UTmxztmQDc298L3"
    - "/ip4/127.0.0.1/tcp/9002/p2p/12D3KooWQYhTNQdmr3ArTeUHRYzFg94BKyTkoWBDWez9kSCVe2Xo"

dkg:
  validator_count: 3
  threshold: 2
  epoch: 0

storage:
  path: "/tmp/zeratul/validator-0"
