validator:
  index: 2
  name: "validator-2"

network:
  listen_addr: "127.0.0.1:9002"
  peers:
    - "/ip4/127.0.0.1/tcp/9000/p2p/12D3KooWPjceQrSwdWXPyLLeABRXmuqt69Rg3sBYbU1Nft9HyQ6X"
    - "/ip4/127.0.0.1/tcp/9001/p2p/12D3KooWH3uVF6wv47WnArKHk5p6cvgCJEb74UTmxztmQDc298L3"

dkg:
  validator_count: 3
  threshold: 2
  epoch: 0

storage:
  path: "/tmp/zeratul/validator-2"
